services:
  db:
    container_name: vp-db
    image: postgres:18-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5433:5432"

  scheduler:
    container_name: vp-scheduler
    image: alpine
    command: >
      sh -c "while true; do
        wget -qO- --post-data='' http://backend:8000/sync-global;
        sleep 21600;
      done"
    depends_on:
      - backend

  backend:
    container_name: vp-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    ports:
      - "8000:8000"

  frontend:
    container_name: vp-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - backend

  evolution_redis:
    container_name: vp-evolution-redis
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - evolution_redis_data:/data

  evolution:
    container_name: vp-evolution
    image: evoapicloud/evolution-api:v2.3.7
    environment:
      - SERVER_URL=http://localhost:8080
      - DOCKER_ENV=true
      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_URI=redis://evolution_redis:6379/0
      - CACHE_REDIS_PREFIX_KEY=evolution
      - AUTHENTICATION_TYPE=apikey
      - AUTHENTICATION_API_KEY=${EVOLUTION_API_KEY}
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/evolution

    ports:
      - "8080:8080"
    depends_on:
      - evolution_redis

volumes:
  postgres_data:
  evolution_redis_data:
